# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eShop
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  target 'eShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eShopUITests' do
    # Pods for testing
  end

end
